version: '3.4'

services:
  voituresexpress:
    image: voituresexpress
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./src/server.js"]
