version: '3.8'

services:
    mysql:
        container_name: express_car_db
        image: mysql
        restart: unless-stopped
        # env_file: ./.env
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - '3306:3306'
        volumes:
            - carsexpress:/var/lib/mysql

    api:
        container_name: express_cars_api
        depends_on:
            - mysql

        build:
            dockerfile: dockerfile
            context: .

        # env_file: ./.env
        volumes:
            - .:/app
        ports:
            - '${PORT}:${PORT}'

        command: npm run start

volumes:
    carsexpress:
